config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener"

  resources :tasks do
    get :assign, on: :member
  end
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "tasks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user, optional: true

  enum status: { 未対応: 1, 対応中: 2, 完了: 3 }
  validates :title, :content, :deadline, :status, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable
  validates :name, :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: %i[ show assign edit update destroy ]
  before_action :check_task_auth, only: %i[ edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    if params[:type] == 'my'
      @tasks = current_user.tasks.where.not(status: '完了')
    else
      @tasks = Task.all
    end

    @q = @tasks.ransack(params[:q])
    @tasks = @q.result(distinct: true)
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  def assign
  end

  # GET /tasks/new
  def new
    @task = Task.new(status: '未対応')
  end

  # GET /tasks/1/edit
  def edit
    origin_url
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params.merge!(creator_id: current_user.id))

    respond_to do |format|
      if @task.save
        format.html { redirect_to task_url(@task), notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update!(task_params)
        format.html { redirect_to cookies[:refer] || tasks_path, notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    def check_task_auth
      redirect_to tasks_path, notice: 'no auth' and return if @task.creator_id != current_user.id
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:title, :content, :deadline, :user_id, :status)
    end

    def origin_url
      cookies[:refer] = request.referer || tasks_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">タスク管理アプリ</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'マイタスク', tasks_path(type: 'my') %></li>
        <li><%= link_to 'タスク一覧', tasks_path %></li>
        <% if user_signed_in? %>
          <li><a href="/users/edit">ユーザ設定</a></li>
          <li><%= link_to 'サインアウト', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><a href="/users/sign_in">サインイン</a></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= simple_form_for(@task) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :content %>
    <%= f.label :deadline %>
    <%= f.datetime_field :deadline, class: 'form-control' %>

    <%= f.label :status %>
    <%= f.radio_button(:status, "未対応") %>
    <%= f.label(:status, "未対応") %>
    <%= f.radio_button(:status, "対応中") %>
    <%= f.label(:status, "対応中") %>
    <% if params[:action] != 'new' %>
      <%= f.radio_button(:status, "完了") %>
      <%= f.label(:status, "完了") %>
    <% end %>
  </div>

  <div class="form-actions">
    <%= f.submit "登録する", class: "btn btn-primary" %>
    
    <%= link_to '戻る', tasks_path, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div class="panel <%= Time.current >= task.deadline ? 'panel-danger' : 'panel-success' %>">
  <div class="panel-heading">タスク <%= task.id %></div>
  <div class="panel-body">
    <p>
      <strong><%= task.title %></strong>
    </p>

    <p>
      <strong>期限:</strong>
      <%= task.deadline.to_date %>
    </p>

    <p>
      <strong>担当者:</strong>
      <%= task.user&.name || 'No Assign' %>
    </p>

    <p>
      <strong>ステータス:</strong>
      <%= task.status %>
    </p>
    <%= link_to '詳細', task, class: 'btn btn-default' %>
    <% if task.creator_id == current_user.id %>
      <%= link_to '編集', edit_task_path(task), class: 'btn btn-info' %>
      <%= link_to "削除", task, method: :delete, class: 'btn btn-danger' %>
    <% end %>
  </div>
</div>

app/views/tasks/assign.html.erb
<p style="color: green"><%= notice %></p>
<h1>アサイン</h1>
<div class="row">
  <div class="col-md-6">
    <p>現在アサインされているユーザ</p>
    <p><%= @task.user&.name || 'No Assign' %></p>
    <% if @task.creator_id == current_user.id %>
      <%= button_tag 'アサインする', class: 'btn btn-success submit-assign' %>
    <% end %>
  </div>
  <% if @task.creator_id == current_user.id %>
    <div class="col-md-6">
      <%= simple_form_for @task do |f| %>
        <%= f.input :user_id, collection: User.all, label: '新しくアサインするユーザ' %>
        <%= f.button :submit, style: 'display: none' %>
      <% end %>
    </div>
  <% end %>
</div>
<div class="pannel">
  <h1><%= @task.title %></h1>

  <p>
    <%= @task.content %>
  </p>

  <p>
    <strong>期限：</strong>
    <%= @task.deadline.to_date %>
  </p>

  <p>
    <strong>ステーター：</strong>
    <%= @task.status %>
  </p>
</div>

<script>
  $('.submit-assign').click(function() {
    $('form').submit();
  });
</script>

app/views/tasks/edit.html.erb
<h1>タスク編集</h1>

<%= render "form", task: @task %>

<br>

app/views/tasks/index.html.erb
<p style="color: green"><%= notice %></p>

<% title = params[:type] == 'my' ? 'マイタスク' : 'タスク一覧' %>

<div style="margin-left: 15px;">
  <h1><%= title %></h1>
  <div class="input-group">
    <%= search_form_for @q do |f| %>
      <%= hidden_field_tag :type, params[:type] %>
      <%= f.search_field :title_cont, class: 'form-control', style: 'width: 200px;', placeholder: 'please input title...' %>
      <div class="input-group-btn">
        <%= f.button 'Search', class: 'btn btn-default' %>
      </div>
    <% end %>
  </div>
  <br>
</div>

<% if params[:type] == 'my' %>
  <%= link_to "新規タスク", new_task_path, class: "btn btn-success", style: 'margin-left: 15px;margin-bottom: 10px;' %>
<% end %>

<div id="tasks">
  <% @tasks.each do |task| %>
    <div class="col-md-4 col-sm-6 col-xs-12">
      <%= render task %>
    </div>
  <% end %>
</div>

app/views/tasks/new.html.erb
<h1>新規タスク</h1>

<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="pannel">
  <h1><%= @task.title %></h1>

  <p>
    <%= @task.content %>
  </p>

  <p>
    <strong>期限：</strong>
    <%= @task.deadline.to_date %>
  </p>

  <p>
    <strong>ステーター：</strong>
    <%= @task.status %>
  </p>

  <p>
    <strong>担当者：</strong>
    <%= @task.user&.name %>
  </p >
  
  <div>
    <%= link_to '戻る', 'javascript:;', class: 'btn btn-default return' %>
    <% if @task.creator_id == current_user.id %>
      <%= link_to '編集', edit_task_path(@task), class: 'btn btn-info' %>
      <%= link_to 'アサイン', assign_task_path(@task), class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

<script>
  $('.submit-assign').click(function() {
    $('form').submit();
  });

  $('.return').click(function() {
    window.history.back();
  });
</script>